export const PRICING = {
  PLUS_MONTHLY_TRY: 59.9,
  PLUS_MONTHLY_LABEL: "59,90 TL",
  CURRENCY: "TRY",
};

export const PLUS_MONTHLY_PRICE = PRICING.PLUS_MONTHLY_TRY;
export const PLUS_MONTHLY_PRICE_LABEL = PRICING.PLUS_MONTHLY_LABEL;
